version = 1

exclude_patterns = [
    "bin/*",
    "debian/*",
    "deploy/*",
    "docker/*",
    "docs/*",
    "For/*",
    "from/*",
    "functionality/*",
    "owtf.egg-info/*",
    "requirements/*",
    "scripts/*",
    "Ssl-Tls/*",
    "testing/*"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
