---
- name: Setup Kali Linux with Docker and OWASP OWTF
  hosts: all
  become: true

  tasks:
    - name: Update apt repository and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes

    - name: Install Docker, Docker-Compose, Git, Curl and Make
      apt:
        name: 
          - docker.io
          - docker-compose
          - curl
          - git
          - make
        state: present

    - name: Add user to docker group
      become: yes
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Notify user of need to log out and back in
      ansible.builtin.debug:
        msg: "NOTE: You'll need to log out and log back in for the group membership to take effect."

    - name: Reset ssh connection to allow user changes to take affect 
      meta: reset_connection

    - name: Clone OWTF repository
      ansible.builtin.shell: |
        git clone https://github.com/owtf/owtf

    - name: Restart Docker service
      ansible.builtin.systemd:
        name: docker
        state: restarted

    - name: Run OWTF using Docker Compose
      ansible.builtin.shell: |
        cd owtf && make compose
...
