apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: owtf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres:alpine
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: db
        volumeMounts:
          - name: db-volume
            mountPath: /db
        ports:
        - containerPort: 5432
      volumes:
      - name: db-volume
        persistentVolumeClaim:
          claimName: db-pvc

