# Stage 1: Build the React app
FROM node:18 AS builder

WORKDIR /owtf-webapp

COPY ./owtf/webapp/package.json ./owtf/webapp/yarn.lock ./
RUN yarn install --silent
COPY ./owtf/webapp .
RUN yarn build
RUN yarn cache clean

EXPOSE 8019

CMD ["yarn", "run", "prod"]
